import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import api from '../services/api'
import { Header } from './components/Header/header'
import { Publicidade } from './components/Publicidade/publicidade'
import S from './index.module.scss'

export type Content = {
  date: string
  resume: string
  text: string
}

type MainData = {
  id: string
  type: string
  categorie: string
  title: string
  content: Content
  img: string
}

type secondaryData = {
  id: string
  type: string
  categorie: string
  title: string
  content: Content
}

interface HomeProps {
  mainData: MainData[]
  secondaryData: secondaryData[]
}

const Home: NextPage<HomeProps> = ({ mainData, secondaryData }) => {
  const [firstMain, setFirstMain] = useState<MainData[]>([])
  const [secondMain, setSecondMain] = useState<MainData[]>([])
  

  useEffect(() => {
    const first = mainData.filter(item => !item.hasOwnProperty('img'))
    const second = mainData.filter(item => item.hasOwnProperty('img'))
    setFirstMain(first)
    setSecondMain(second)
  }, [mainData])
  return (
    <>
      <Head>
        <title>T-SEVN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h1>SEVN NEWS</h1>
      </Header>
      <main className={S.container}>
        <Publicidade>
          <h1>Publicidade</h1>
        </Publicidade>       
        <section className={S.content}>
          {!!firstMain.length && firstMain.map((news) => (
            <Link href={`/news/${news.id}`} key={news.id}>
              <a className={S.contentMain} >
                <strong>{news.categorie.toUpperCase()}</strong>
                <h2>{news.title}</h2>
              </a>
            </Link>
          ))}          
          <div className={S.contentWithImg}>
            {!!secondMain.length && secondMain.map((news) => (
              <Link href={`/news/${news.id}`} key={news.id}>
                <a>
                  <Image src={news.img} alt={news.title} width={280} height={190} />
                  <strong className={S[news.categorie]}>{news.categorie.toUpperCase()}</strong>
                  <p>{news.title}</p>
                </a>
              </Link>
            ))}
          </div>
        </section>
        <section className={S.sectionSecondary}>
          <div className={S.secondary}>
            {!!secondaryData.length && secondaryData.map(news => (
              <Link href={`/news/${news.id}`} key={news.id}>
                <a className={S[news.categorie]}>
                  <p>{news.title}</p>
                </a>
              </Link>
            ))}
            </div>
        </section>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const [main, secondary] = await Promise.all([api.get('/news'), api.get('/news/secondary')])

  const mainData = main?.data
  const secondaryData = secondary?.data

  return {
    props: {
      mainData,
      secondaryData
    },
  }
}

export default Home
