import type { NextPage } from 'next'
import Head from 'next/head'
import S from './index.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T-SEVN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={S.header}>
        <h1>SEVN NEWS</h1>
      </header>
      <main>
        
      </main>
    </>
  )
}

export default Home
